options:
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'create', '--name', 'builder']
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'use', 'builder']
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'build', '--build-arg', 'BUILDKIT_INLINE_CACHE=1', '-f', 'src/cmd/cos_gpu_config_builder/Dockerfile', '--cache-from', 'gcr.io/${_OUTPUT_PROJECT}/cos-gpu-config-builder:latest', '-t', 'gcr.io/${_OUTPUT_PROJECT}/cos-gpu-config-builder:${TAG_NAME}', '-t', 'gcr.io/${_OUTPUT_PROJECT}/cos-gpu-config-builder:latest', '--push', '.']
